SET search_path TO core, public;

-- Work Activities (Summary – OnLine box)
CREATE TABLE IF NOT EXISTS core.career_work_activities (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onet_code   TEXT NOT NULL,
  activity    TEXT NOT NULL,
  -- optional: description TEXT
  source      TEXT NOT NULL DEFAULT 'ONLINE',
  fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_career_work_activities
  ON core.career_work_activities (onet_code, activity);

-- Detailed Work Activities (DWAs)
CREATE TABLE IF NOT EXISTS core.career_dwas (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onet_code   TEXT NOT NULL,
  dwa         TEXT NOT NULL,
  source      TEXT NOT NULL DEFAULT 'ONLINE',
  fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_career_dwas
  ON core.career_dwas (onet_code, dwa);

-- Work Context (Summary – OnLine box)
CREATE TABLE IF NOT EXISTS core.career_work_context (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onet_code   TEXT NOT NULL,
  context     TEXT NOT NULL,
  -- optional: percent_or_label TEXT
  source      TEXT NOT NULL DEFAULT 'ONLINE',
  fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_career_work_context
  ON core.career_work_context (onet_code, context);

-- (tuỳ chọn nếu muốn %Education như OnLine)
CREATE TABLE IF NOT EXISTS core.career_education_pct (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onet_code   TEXT NOT NULL,
  label       TEXT NOT NULL,   -- Bachelor's degree / Associate's degree / ...
  pct         NUMERIC,         -- 46 / 17 / 17 ...
  source      TEXT NOT NULL DEFAULT 'ONLINE',
  fetched_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_career_education_pct
  ON core.career_education_pct (onet_code, label);
