"""
Seed virtual mentor profiles for all 22 career groups.
Creates 3 mentors per group = 66 total demo mentors.
"""
import os, sys, random
sys.path.insert(0, '.')
from dotenv import load_dotenv; load_dotenv('.env')

from app.core.db import SessionLocal
from app.modules.auth.models import User
from app.modules.mentor_matching.models import MentorProfile

import bcrypt as _bcrypt
DEMO_PASSWORD = _bcrypt.hashpw(b"Demo12345", _bcrypt.gensalt()).decode()

# ── Mentor data per career group ─────────────────────────────────────────────
MENTORS = {
    "management": [
        {"name": "Nguyen Van Minh", "position": "CEO & Founder", "company": "VinTech Solutions",
         "bio": "20 nam kinh nghiem quan ly doanh nghiep, chuyen gia chien luoc phat trien to chuc.",
         "skills": ["Strategic Planning", "Leadership", "Business Development", "Team Management", "OKR"],
         "yoe": 20, "riasec": {"E": 5, "S": 4, "C": 3, "I": 2, "R": 1, "A": 2},
         "big5": {"openness": 4.2, "conscientiousness": 4.8, "extraversion": 4.5, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Tran Bich Hang", "position": "COO", "company": "FPT Software",
         "bio": "Chuyen gia van hanh doanh nghiep, quan ly du an lon.",
         "skills": ["Operations Management", "Process Optimization", "Project Management", "Change Management"],
         "yoe": 15, "riasec": {"E": 4, "C": 5, "S": 3, "I": 3, "R": 2, "A": 1},
         "big5": {"openness": 3.8, "conscientiousness": 5.0, "extraversion": 4.0, "agreeableness": 4.0, "neuroticism": 1.8}},
        {"name": "Le Hoang Nam", "position": "General Manager", "company": "Masan Group",
         "bio": "Quan ly doanh nghiep da quoc gia, xay dung doi ngu lanh dao.",
         "skills": ["P&L Management", "Stakeholder Management", "Executive Leadership", "Mergers & Acquisitions"],
         "yoe": 18, "riasec": {"E": 5, "C": 4, "S": 4, "I": 2, "R": 1, "A": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.6, "extraversion": 4.8, "agreeableness": 3.5, "neuroticism": 1.2}},
    ],
    "business-finance": [
        {"name": "Pham Thanh Tung", "position": "CFO", "company": "Techcombank",
         "bio": "Chuyen gia tai chinh doanh nghiep, IPO, phan tich dau tu.",
         "skills": ["Financial Analysis", "Corporate Finance", "Investment Banking", "Financial Modeling", "Excel"],
         "yoe": 16, "riasec": {"C": 5, "I": 4, "E": 3, "S": 2, "R": 2, "A": 1},
         "big5": {"openness": 3.5, "conscientiousness": 4.9, "extraversion": 3.5, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Nguyen Thi Mai", "position": "Senior Financial Analyst", "company": "Vietcombank",
         "bio": "Phan tich tai chinh, bao cao, lam viec voi doanh nghiep lon.",
         "skills": ["Financial Reporting", "Budgeting", "Cost Analysis", "Risk Management", "IFRS"],
         "yoe": 10, "riasec": {"C": 5, "I": 4, "E": 2, "S": 3, "R": 1, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.7, "extraversion": 3.2, "agreeableness": 4.0, "neuroticism": 2.0}},
        {"name": "Do Quang Huy", "position": "Investment Director", "company": "VinaCapital",
         "bio": "Quan ly quy dau tu, phan tich co phieu, danh gia rui ro.",
         "skills": ["Portfolio Management", "Equity Research", "Valuation", "Due Diligence", "CFA"],
         "yoe": 14, "riasec": {"I": 5, "C": 4, "E": 3, "S": 2, "R": 1, "A": 2},
         "big5": {"openness": 4.2, "conscientiousness": 4.5, "extraversion": 3.8, "agreeableness": 3.5, "neuroticism": 1.8}},
    ],
    "computer-math": [
        {"name": "Vo Minh Duc", "position": "Senior Software Engineer", "company": "Google Vietnam",
         "bio": "10 nam kinh nghiem phat trien phan mem, chuyen gia backend va cloud.",
         "skills": ["Python", "Java", "Microservices", "AWS", "System Design", "Kubernetes"],
         "yoe": 10, "riasec": {"I": 5, "R": 4, "C": 3, "E": 2, "S": 2, "A": 2},
         "big5": {"openness": 4.5, "conscientiousness": 4.3, "extraversion": 2.8, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Nguyen Bao Khanh", "position": "AI/ML Engineer", "company": "VinAI",
         "bio": "Nghien cuu va ung dung AI, deep learning, NLP cho san pham thuc te.",
         "skills": ["Machine Learning", "Deep Learning", "Python", "TensorFlow", "NLP", "Computer Vision"],
         "yoe": 8, "riasec": {"I": 5, "R": 4, "C": 3, "A": 3, "E": 2, "S": 2},
         "big5": {"openness": 4.8, "conscientiousness": 4.0, "extraversion": 2.5, "agreeableness": 3.5, "neuroticism": 2.0}},
        {"name": "Tran Phuong Linh", "position": "Full Stack Developer", "company": "Axon Active",
         "bio": "Phat trien web ung dung day du stack, chuyen tu React den Node.js.",
         "skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "Docker", "REST API"],
         "yoe": 7, "riasec": {"I": 4, "R": 4, "C": 3, "A": 3, "E": 2, "S": 2},
         "big5": {"openness": 4.2, "conscientiousness": 4.2, "extraversion": 3.0, "agreeableness": 4.0, "neuroticism": 1.8}},
    ],
    "architecture-engineering": [
        {"name": "Hoang Trung Kien", "position": "Senior Civil Engineer", "company": "CIENCO 4",
         "bio": "Thiet ke ket cau cong trinh, quan ly du an xay dung ha tang.",
         "skills": ["AutoCAD", "Structural Design", "Project Management", "Civil Engineering", "BIM"],
         "yoe": 15, "riasec": {"R": 5, "I": 4, "C": 4, "E": 2, "S": 2, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.8, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Pham Thi Thu Hoa", "position": "Architect", "company": "Nikken Sekkei Vietnam",
         "bio": "Thiet ke kien truc nha o, thuong mai, chuyen gia BIM.",
         "skills": ["Architecture Design", "Revit", "SketchUp", "BIM", "Urban Planning", "Sustainable Design"],
         "yoe": 12, "riasec": {"A": 5, "R": 4, "I": 3, "E": 2, "S": 2, "C": 3},
         "big5": {"openness": 4.8, "conscientiousness": 4.0, "extraversion": 3.5, "agreeableness": 4.0, "neuroticism": 2.0}},
        {"name": "Le Van Cuong", "position": "Electrical Engineer", "company": "Siemens Vietnam",
         "bio": "Ky su dien cong nghiep, tu dong hoa nha may.",
         "skills": ["PLC Programming", "Electrical Design", "SCADA", "AutoCAD Electrical", "Industrial Automation"],
         "yoe": 13, "riasec": {"R": 5, "I": 5, "C": 3, "E": 2, "S": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.7, "extraversion": 2.8, "agreeableness": 3.5, "neuroticism": 1.5}},
    ],
    "life-science": [
        {"name": "Nguyen Thi Lan Anh", "position": "Research Scientist", "company": "Institut Pasteur",
         "bio": "Nghien cuu vi sinh vat, phat trien vaccine, phan tich phong thi nghiem.",
         "skills": ["Molecular Biology", "PCR", "Cell Culture", "Bioinformatics", "Research Methods"],
         "yoe": 12, "riasec": {"I": 5, "R": 4, "C": 3, "S": 2, "E": 2, "A": 3},
         "big5": {"openness": 4.8, "conscientiousness": 4.5, "extraversion": 2.8, "agreeableness": 4.0, "neuroticism": 1.8}},
        {"name": "Tran Quoc Bao", "position": "Biotech Engineer", "company": "BioVarco",
         "bio": "Ky thuat sinh hoc, phat trien san pham thuc pham va duoc pham.",
         "skills": ["Biotechnology", "CRISPR", "Fermentation", "GMP", "Quality Control"],
         "yoe": 9, "riasec": {"I": 5, "R": 4, "C": 4, "A": 2, "E": 2, "S": 2},
         "big5": {"openness": 4.5, "conscientiousness": 4.5, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Do Thi Bich Ngoc", "position": "Environmental Scientist", "company": "IUCN Vietnam",
         "bio": "Nghien cuu moi truong, bien doi khi hau, quan ly tai nguyen thien nhien.",
         "skills": ["Environmental Assessment", "GIS", "Climate Science", "Data Analysis", "Field Research"],
         "yoe": 11, "riasec": {"I": 4, "R": 3, "S": 4, "C": 3, "E": 3, "A": 3},
         "big5": {"openness": 4.6, "conscientiousness": 4.2, "extraversion": 3.5, "agreeableness": 4.5, "neuroticism": 1.8}},
    ],
    "community-social": [
        {"name": "Vu Thi Thu Ha", "position": "Social Worker", "company": "UNICEF Vietnam",
         "bio": "Cong tac xa hoi, bao ve tre em, phat trien cong dong.",
         "skills": ["Social Work", "Case Management", "Community Development", "Child Protection", "Counseling"],
         "yoe": 10, "riasec": {"S": 5, "A": 3, "E": 3, "I": 2, "R": 1, "C": 3},
         "big5": {"openness": 4.2, "conscientiousness": 4.0, "extraversion": 4.2, "agreeableness": 4.8, "neuroticism": 2.0}},
        {"name": "Nguyen Hoang Giang", "position": "NGO Program Manager", "company": "Save the Children",
         "bio": "Quan ly chuong trinh phat trien cong dong, nang cao nang luc.",
         "skills": ["Program Management", "Grant Writing", "Community Engagement", "M&E", "Fundraising"],
         "yoe": 12, "riasec": {"S": 5, "E": 4, "A": 3, "I": 3, "C": 3, "R": 1},
         "big5": {"openness": 4.5, "conscientiousness": 4.2, "extraversion": 4.5, "agreeableness": 4.8, "neuroticism": 1.5}},
        {"name": "Le Thi Kim Oanh", "position": "Psychologist", "company": "Hanoi Family Psychology",
         "bio": "Tam ly hoc gia dinh va tre em, tu van suc khoe tam than.",
         "skills": ["Psychology", "Counseling", "Cognitive Behavioral Therapy", "Mental Health", "Child Development"],
         "yoe": 13, "riasec": {"S": 5, "I": 4, "A": 3, "E": 2, "C": 3, "R": 1},
         "big5": {"openness": 4.5, "conscientiousness": 4.3, "extraversion": 3.8, "agreeableness": 4.9, "neuroticism": 2.0}},
    ],
    "legal": [
        {"name": "Nguyen Duc Thanh", "position": "Senior Lawyer", "company": "Vilaf Law Firm",
         "bio": "Luat su doanh nghiep, hop dong thuong mai, tu van phap ly dau tu nuoc ngoai.",
         "skills": ["Corporate Law", "Contract Law", "M&A", "Legal Drafting", "Litigation"],
         "yoe": 16, "riasec": {"E": 4, "I": 4, "C": 5, "S": 3, "A": 2, "R": 1},
         "big5": {"openness": 3.8, "conscientiousness": 4.8, "extraversion": 4.0, "agreeableness": 3.5, "neuroticism": 1.5}},
        {"name": "Pham Nguyen Bao Chau", "position": "IP Attorney", "company": "Novatek",
         "bio": "Luat su so huu tri tue, bang sang che, ban quyen.",
         "skills": ["Intellectual Property", "Patent Law", "Trademark", "Copyright", "IP Strategy"],
         "yoe": 11, "riasec": {"I": 5, "C": 5, "E": 3, "S": 2, "R": 2, "A": 2},
         "big5": {"openness": 4.2, "conscientiousness": 4.9, "extraversion": 3.5, "agreeableness": 3.8, "neuroticism": 1.8}},
        {"name": "Vo Thi Hong Nhung", "position": "Compliance Officer", "company": "HSBC Vietnam",
         "bio": "Quan ly tuan thu phap luat tai chinh ngan hang, AML.",
         "skills": ["Regulatory Compliance", "AML", "Risk Management", "Banking Law", "Internal Audit"],
         "yoe": 9, "riasec": {"C": 5, "I": 4, "E": 3, "S": 2, "R": 1, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 5.0, "extraversion": 3.2, "agreeableness": 3.8, "neuroticism": 1.5}},
    ],
    "education": [
        {"name": "Tran Thi Minh Tam", "position": "University Lecturer", "company": "Hanoi University of Science",
         "bio": "Giang day CNTT, nghien cuu khoa hoc du lieu, huong dan sinh vien.",
         "skills": ["Teaching", "Curriculum Design", "Data Science", "Python", "Academic Research"],
         "yoe": 14, "riasec": {"S": 4, "I": 5, "A": 3, "E": 3, "C": 3, "R": 2},
         "big5": {"openness": 4.8, "conscientiousness": 4.3, "extraversion": 3.8, "agreeableness": 4.5, "neuroticism": 1.8}},
        {"name": "Nguyen Thanh Phong", "position": "Education Consultant", "company": "IDP Education",
         "bio": "Tu van du hoc, phat trien chuong trinh dao tao quoc te.",
         "skills": ["Educational Consulting", "Curriculum Development", "Career Guidance", "Study Abroad", "English"],
         "yoe": 10, "riasec": {"S": 5, "E": 4, "A": 3, "I": 3, "C": 2, "R": 1},
         "big5": {"openness": 4.3, "conscientiousness": 4.0, "extraversion": 4.5, "agreeableness": 4.8, "neuroticism": 1.5}},
        {"name": "Bui Thi Lan", "position": "Training Manager", "company": "VTC Academy",
         "bio": "Thiet ke chuong trinh dao tao ky nang mem, quan ly hoc vien.",
         "skills": ["Training Design", "Soft Skills", "E-learning", "LMS", "Facilitation"],
         "yoe": 12, "riasec": {"S": 5, "A": 4, "E": 4, "I": 2, "C": 3, "R": 1},
         "big5": {"openness": 4.5, "conscientiousness": 4.2, "extraversion": 4.5, "agreeableness": 4.7, "neuroticism": 1.8}},
    ],
    "arts-media": [
        {"name": "Dang Minh Hieu", "position": "Creative Director", "company": "Ogilvy Vietnam",
         "bio": "10 nam trong quang cao sang tao, thuong hieu va digital marketing.",
         "skills": ["Creative Direction", "Brand Strategy", "Copywriting", "Art Direction", "Adobe Creative Suite"],
         "yoe": 10, "riasec": {"A": 5, "E": 4, "S": 3, "I": 3, "R": 2, "C": 2},
         "big5": {"openness": 5.0, "conscientiousness": 3.5, "extraversion": 4.2, "agreeableness": 3.8, "neuroticism": 2.5}},
        {"name": "Nguyen Thi Quynh Anh", "position": "UX/UI Designer", "company": "Grab Vietnam",
         "bio": "Thiet ke trai nghiem nguoi dung, nghien cuu nguoi dung, prototyping.",
         "skills": ["UX Design", "UI Design", "Figma", "User Research", "Prototyping", "Design Systems"],
         "yoe": 7, "riasec": {"A": 5, "I": 4, "R": 3, "S": 3, "E": 2, "C": 3},
         "big5": {"openness": 4.8, "conscientiousness": 4.0, "extraversion": 3.5, "agreeableness": 4.2, "neuroticism": 2.0}},
        {"name": "Tran Van Huy", "position": "Content Creator & Director", "company": "Yeah1 Network",
         "bio": "San xuat noi dung video, truyen thong so, phim quang cao.",
         "skills": ["Video Production", "Scriptwriting", "Adobe Premiere", "After Effects", "Social Media"],
         "yoe": 9, "riasec": {"A": 5, "E": 4, "S": 3, "I": 2, "R": 3, "C": 2},
         "big5": {"openness": 4.9, "conscientiousness": 3.8, "extraversion": 4.5, "agreeableness": 4.0, "neuroticism": 2.2}},
    ],
    "healthcare-practitioners": [
        {"name": "Bac si Nguyen Van An", "position": "Senior Physician", "company": "Bach Mai Hospital",
         "bio": "Bac si noi khoa 20 nam kinh nghiem, chuyen gia benh tim mach.",
         "skills": ["Internal Medicine", "Cardiology", "Clinical Diagnosis", "Patient Care", "Medical Research"],
         "yoe": 20, "riasec": {"I": 5, "S": 4, "R": 3, "C": 4, "E": 3, "A": 2},
         "big5": {"openness": 4.2, "conscientiousness": 4.8, "extraversion": 3.5, "agreeableness": 4.5, "neuroticism": 1.5}},
        {"name": "Nguyen Thi Phuong Thao", "position": "Pharmacist", "company": "Pymepharco",
         "bio": "Duoc sy lam sang, nghien cuu phat trien thuoc moi.",
         "skills": ["Pharmacology", "Drug Development", "Clinical Trials", "Regulatory Affairs", "Chemistry"],
         "yoe": 12, "riasec": {"I": 5, "R": 4, "C": 5, "S": 3, "E": 2, "A": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.9, "extraversion": 3.0, "agreeableness": 4.2, "neuroticism": 1.8}},
        {"name": "Le Thanh Hai", "position": "Dental Specialist", "company": "Nha Khoa Paris",
         "bio": "Nha khoa tham my va chinh nha, su dung cong nghe hien dai.",
         "skills": ["Dental Surgery", "Orthodontics", "Digital Dentistry", "Patient Management", "3D Imaging"],
         "yoe": 15, "riasec": {"R": 4, "I": 4, "S": 4, "C": 4, "E": 3, "A": 3},
         "big5": {"openness": 3.8, "conscientiousness": 4.7, "extraversion": 3.8, "agreeableness": 4.5, "neuroticism": 1.5}},
    ],
    "healthcare-support": [
        {"name": "Pham Thi Bich Thuy", "position": "Head Nurse", "company": "Vinmec Hospital",
         "bio": "Dieu duong chuyen nghiep, quan ly phong benh, cham soc benh nhan.",
         "skills": ["Patient Care", "Nursing", "ICU", "Medical Procedures", "Team Leadership"],
         "yoe": 15, "riasec": {"S": 5, "R": 4, "C": 4, "I": 3, "E": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.8, "extraversion": 3.8, "agreeableness": 4.9, "neuroticism": 1.8}},
        {"name": "Nguyen Minh Quang", "position": "Physical Therapist", "company": "Sports Medicine Vietnam",
         "bio": "Vat ly tri lieu cho van dong vien va nguoi bi chan thuong.",
         "skills": ["Physical Therapy", "Rehabilitation", "Sports Medicine", "Anatomy", "Exercise Science"],
         "yoe": 10, "riasec": {"S": 5, "R": 4, "I": 3, "C": 3, "E": 2, "A": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.5, "extraversion": 4.0, "agreeableness": 4.8, "neuroticism": 1.5}},
        {"name": "Tran Bao Ngoc", "position": "Medical Lab Technician", "company": "LabVina",
         "bio": "Ky thuat vien phong xet nghiem, quan ly mau va ket qua.",
         "skills": ["Laboratory Techniques", "Blood Analysis", "Microbiology", "Quality Control", "Lab Management"],
         "yoe": 8, "riasec": {"R": 4, "I": 5, "C": 4, "S": 3, "E": 1, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.9, "extraversion": 2.8, "agreeableness": 4.0, "neuroticism": 1.5}},
    ],
    "protective-service": [
        {"name": "Hoang Van Thanh", "position": "Security Manager", "company": "G4S Vietnam",
         "bio": "Quan ly an ninh toa nha va su kien lon, dao tao bao ve.",
         "skills": ["Security Management", "Risk Assessment", "Emergency Response", "CCTV", "Team Leadership"],
         "yoe": 18, "riasec": {"R": 5, "E": 4, "S": 3, "C": 4, "I": 2, "A": 1},
         "big5": {"openness": 3.2, "conscientiousness": 4.7, "extraversion": 4.0, "agreeableness": 3.5, "neuroticism": 1.5}},
        {"name": "Nguyen Van Dung", "position": "Fire Safety Specialist", "company": "PCCC Vietnam",
         "bio": "Chuyen gia an toan phong chay chua chay, kiem tra he thong.",
         "skills": ["Fire Safety", "Emergency Planning", "Risk Assessment", "Safety Regulations", "Training"],
         "yoe": 14, "riasec": {"R": 5, "C": 4, "S": 3, "I": 3, "E": 3, "A": 1},
         "big5": {"openness": 3.5, "conscientiousness": 4.8, "extraversion": 3.5, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Le Thi Minh", "position": "Cyber Security Analyst", "company": "Viettel Cyber Security",
         "bio": "Phan tich bao mat thong tin, ngan chan tan cong mang.",
         "skills": ["Cybersecurity", "Penetration Testing", "SIEM", "Incident Response", "Network Security"],
         "yoe": 9, "riasec": {"I": 5, "R": 4, "C": 4, "E": 2, "S": 2, "A": 2},
         "big5": {"openness": 4.3, "conscientiousness": 4.5, "extraversion": 2.8, "agreeableness": 3.5, "neuroticism": 1.8}},
    ],
    "food-service": [
        {"name": "Tran Van Duc", "position": "Executive Chef", "company": "Caravelle Hotel Saigon",
         "bio": "Bep truong khach san 5 sao, chuyen mon am thuc Viet va quoc te.",
         "skills": ["Culinary Arts", "Menu Planning", "Food Safety", "Kitchen Management", "Plating"],
         "yoe": 20, "riasec": {"R": 4, "A": 5, "S": 3, "E": 3, "C": 3, "I": 2},
         "big5": {"openness": 4.8, "conscientiousness": 4.2, "extraversion": 3.8, "agreeableness": 3.8, "neuroticism": 2.0}},
        {"name": "Nguyen Thi Ngoc Bich", "position": "F&B Manager", "company": "Golden Gate Restaurant Group",
         "bio": "Quan ly nha hang va quan ly chat luong dich vu am thuc.",
         "skills": ["Restaurant Management", "Food & Beverage", "Staff Training", "Cost Control", "Customer Service"],
         "yoe": 12, "riasec": {"E": 4, "S": 5, "C": 4, "R": 2, "I": 2, "A": 3},
         "big5": {"openness": 4.0, "conscientiousness": 4.5, "extraversion": 4.5, "agreeableness": 4.5, "neuroticism": 2.0}},
        {"name": "Pham Quoc Khanh", "position": "Barista Champion", "company": "The Coffee House",
         "bio": "Vo dich barista quoc gia, chuyen gia ve ca phe specialty.",
         "skills": ["Coffee Science", "Barista Skills", "Latte Art", "Coffee Training", "Quality Control"],
         "yoe": 8, "riasec": {"R": 3, "A": 5, "S": 4, "I": 3, "C": 3, "E": 3},
         "big5": {"openness": 4.8, "conscientiousness": 4.0, "extraversion": 4.2, "agreeableness": 4.5, "neuroticism": 2.0}},
    ],
    "building-maintenance": [
        {"name": "Nguyen Cong Thanh", "position": "Facilities Manager", "company": "Savills Vietnam",
         "bio": "Quan ly toa nha van phong hang A, dieu hanh ky thuat.",
         "skills": ["Facilities Management", "HVAC", "Electrical Systems", "Maintenance Planning", "FM Software"],
         "yoe": 17, "riasec": {"R": 5, "C": 4, "E": 3, "I": 3, "S": 2, "A": 1},
         "big5": {"openness": 3.5, "conscientiousness": 4.8, "extraversion": 3.5, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Vo Van Toan", "position": "MEP Engineer", "company": "Coteccons",
         "bio": "Ky su co dien lanh cong trinh dan dung va cong nghiep.",
         "skills": ["MEP Engineering", "HVAC Design", "Plumbing", "Electrical Systems", "AutoCAD MEP"],
         "yoe": 13, "riasec": {"R": 5, "I": 4, "C": 4, "E": 2, "S": 2, "A": 1},
         "big5": {"openness": 3.5, "conscientiousness": 4.7, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Tran Van Hung", "position": "Property Manager", "company": "CBRE Vietnam",
         "bio": "Quan ly bat dong san thuong mai, toa nha van phong.",
         "skills": ["Property Management", "Lease Management", "Building Operations", "Tenant Relations", "Real Estate"],
         "yoe": 14, "riasec": {"E": 4, "C": 4, "S": 3, "R": 3, "I": 2, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.5, "extraversion": 4.0, "agreeableness": 4.0, "neuroticism": 1.8}},
    ],
    "personal-care": [
        {"name": "Nguyen Thi Bao Ngoc", "position": "Beauty Salon Owner", "company": "Ngoc Beauty Studio",
         "bio": "Chu salon lam dep, chuyen gia trang diem va cham soc da.",
         "skills": ["Skincare", "Makeup Artistry", "Hair Styling", "Beauty Business", "Customer Service"],
         "yoe": 12, "riasec": {"A": 4, "S": 5, "E": 4, "R": 3, "C": 2, "I": 2},
         "big5": {"openness": 4.5, "conscientiousness": 4.0, "extraversion": 4.8, "agreeableness": 4.8, "neuroticism": 2.0}},
        {"name": "Le Thi Thanh Huong", "position": "Fitness Trainer", "company": "California Fitness Vietnam",
         "bio": "Huan luyen vien the hinh, yoga, suc khoe cong dong.",
         "skills": ["Personal Training", "Fitness Coaching", "Nutrition", "Yoga", "Group Exercise"],
         "yoe": 9, "riasec": {"R": 4, "S": 5, "E": 4, "A": 3, "I": 2, "C": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.2, "extraversion": 4.8, "agreeableness": 4.8, "neuroticism": 1.5}},
        {"name": "Pham Van Cuong", "position": "Spa Director", "company": "Six Senses Spa",
         "bio": "Giam doc spa cao cap, chuyen gia lieu phap Dong Tay.",
         "skills": ["Spa Management", "Wellness Therapy", "Aromatherapy", "Massage Therapy", "Business Operations"],
         "yoe": 15, "riasec": {"S": 5, "A": 4, "E": 3, "R": 3, "I": 2, "C": 3},
         "big5": {"openness": 4.5, "conscientiousness": 4.3, "extraversion": 4.2, "agreeableness": 4.8, "neuroticism": 1.8}},
    ],
    "sales": [
        {"name": "Nguyen Van Truong", "position": "Sales Director", "company": "Microsoft Vietnam",
         "bio": "20 nam ban hang B2B, phat trien doi ngu kinh doanh tech.",
         "skills": ["Sales Strategy", "B2B Sales", "Account Management", "CRM", "Sales Training", "Negotiation"],
         "yoe": 20, "riasec": {"E": 5, "S": 4, "C": 3, "I": 2, "A": 2, "R": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.3, "extraversion": 5.0, "agreeableness": 4.0, "neuroticism": 1.5}},
        {"name": "Tran Thi Mai Huong", "position": "Key Account Manager", "company": "Unilever Vietnam",
         "bio": "Quan ly khach hang chien luoc, phan phoi hang tieu dung nhanh.",
         "skills": ["Key Account Management", "FMCG", "Trade Marketing", "Distribution", "Sales Analytics"],
         "yoe": 12, "riasec": {"E": 5, "S": 4, "C": 4, "I": 2, "A": 2, "R": 1},
         "big5": {"openness": 3.8, "conscientiousness": 4.5, "extraversion": 4.8, "agreeableness": 4.2, "neuroticism": 1.8}},
        {"name": "Le Hoang Minh", "position": "Digital Sales Manager", "company": "Lazada Vietnam",
         "bio": "Ban hang thuong mai dien tu, toi uu chuyen doi va doanh thu online.",
         "skills": ["E-commerce", "Digital Marketing", "Performance Marketing", "Conversion Optimization", "SEO"],
         "yoe": 8, "riasec": {"E": 4, "I": 4, "C": 3, "S": 3, "A": 3, "R": 2},
         "big5": {"openness": 4.5, "conscientiousness": 4.2, "extraversion": 4.5, "agreeableness": 3.8, "neuroticism": 2.0}},
    ],
    "office-admin": [
        {"name": "Nguyen Thi Kim Chi", "position": "Office Manager", "company": "WeWork Vietnam",
         "bio": "Quan ly hanh chinh van phong, to chuc su kien, quan ly quy.",
         "skills": ["Office Management", "Administrative Support", "Event Planning", "Budget Management", "MS Office"],
         "yoe": 14, "riasec": {"C": 5, "S": 4, "E": 3, "R": 2, "I": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 5.0, "extraversion": 3.8, "agreeableness": 4.5, "neuroticism": 1.5}},
        {"name": "Tran Quang Huy", "position": "HR Manager", "company": "Nestlé Vietnam",
         "bio": "Quan ly nhan su, tuyen dung, dao tao va phat trien nhan vien.",
         "skills": ["Human Resources", "Recruitment", "Training & Development", "HRIS", "Labor Law"],
         "yoe": 13, "riasec": {"S": 5, "E": 4, "C": 4, "I": 3, "A": 2, "R": 1},
         "big5": {"openness": 4.0, "conscientiousness": 4.5, "extraversion": 4.2, "agreeableness": 4.8, "neuroticism": 1.5}},
        {"name": "Pham Thi Thu Trang", "position": "Executive Assistant", "company": "Deloitte Vietnam",
         "bio": "Thu ky dieu hanh cap cao, lap lich, quan ly thong tin.",
         "skills": ["Executive Support", "Calendar Management", "Travel Coordination", "Report Writing", "Multitasking"],
         "yoe": 10, "riasec": {"C": 5, "S": 4, "E": 3, "R": 2, "I": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.9, "extraversion": 3.5, "agreeableness": 4.5, "neuroticism": 1.8}},
    ],
    "farming-forestry": [
        {"name": "Nguyen Van Cuong", "position": "Agricultural Engineer", "company": "TH True Milk",
         "bio": "Ky su nong nghiep, quan ly trang trai hien dai, cong nghe cao.",
         "skills": ["Agricultural Engineering", "Precision Farming", "Soil Science", "Crop Management", "GIS"],
         "yoe": 16, "riasec": {"R": 5, "I": 4, "C": 3, "S": 2, "E": 2, "A": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.5, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Le Thi Lan Huong", "position": "Aquaculture Specialist", "company": "Minh Phu Seafood",
         "bio": "Nuoi trong thuy san xuat khau, quan ly chat luong san pham.",
         "skills": ["Aquaculture", "Fish Farming", "Water Quality", "Feed Management", "Export Standards"],
         "yoe": 12, "riasec": {"R": 5, "I": 4, "S": 3, "C": 4, "E": 2, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.5, "extraversion": 3.0, "agreeableness": 4.0, "neuroticism": 1.8}},
        {"name": "Tran Minh Toan", "position": "Forestry Manager", "company": "Dong Nai Forest",
         "bio": "Quan ly rung ben vung, bao ve da dang sinh hoc.",
         "skills": ["Forestry Management", "Biodiversity", "Carbon Credits", "GIS", "Environmental Policy"],
         "yoe": 18, "riasec": {"R": 5, "I": 4, "S": 3, "C": 3, "E": 2, "A": 3},
         "big5": {"openness": 4.2, "conscientiousness": 4.3, "extraversion": 2.8, "agreeableness": 4.2, "neuroticism": 1.5}},
    ],
    "construction": [
        {"name": "Nguyen Huu Duc", "position": "Construction Project Manager", "company": "Hoa Binh Construction",
         "bio": "Quan ly du an xay dung cao oc va khu do thi.",
         "skills": ["Construction Management", "Project Planning", "MS Project", "Safety Management", "Primavera"],
         "yoe": 18, "riasec": {"R": 5, "E": 4, "C": 4, "I": 2, "S": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.8, "extraversion": 4.0, "agreeableness": 3.5, "neuroticism": 1.5}},
        {"name": "Vo Thi Thu Thao", "position": "Quantity Surveyor", "command": "Novaland",
         "bio": "Du toan cong trinh, quan ly chi phi xay dung.",
         "skills": ["Quantity Surveying", "Cost Estimation", "Contract Management", "BOQ", "Value Engineering"],
         "yoe": 10, "riasec": {"C": 5, "R": 4, "I": 4, "E": 2, "S": 2, "A": 1},
         "bio": "Du toan cong trinh, quan ly chi phi xay dung.",
         "company": "Novaland",
         "yoe": 10, "riasec": {"C": 5, "R": 4, "I": 4, "E": 2, "S": 2, "A": 1},
         "big5": {"openness": 3.5, "conscientiousness": 4.9, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Pham Minh Duc", "position": "Site Engineer", "company": "Vingroup Construction",
         "bio": "Ky su cong truong, giam sat chat luong thi cong.",
         "skills": ["Site Management", "Quality Control", "Technical Drawing", "Concrete Technology", "Safety"],
         "yoe": 9, "riasec": {"R": 5, "C": 4, "I": 3, "E": 2, "S": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.7, "extraversion": 3.2, "agreeableness": 3.8, "neuroticism": 1.5}},
    ],
    "installation-repair": [
        {"name": "Nguyen Van Long", "position": "Senior Technician", "company": "Samsung Service Center",
         "bio": "Ky thuat vien dien tu, sua chua thiet bi dien tu cong nghiep.",
         "skills": ["Electronics Repair", "Diagnostic Testing", "Soldering", "PLC", "Technical Support"],
         "yoe": 15, "riasec": {"R": 5, "I": 4, "C": 3, "S": 2, "E": 2, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.7, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Tran Thi Phuong", "position": "HVAC Technician Lead", "company": "Johnson Controls",
         "bio": "Ky thuat truong he thong dieu hoa khong khi toa nha.",
         "skills": ["HVAC Systems", "Refrigeration", "Energy Management", "Preventive Maintenance", "BAS"],
         "yoe": 12, "riasec": {"R": 5, "I": 4, "C": 3, "S": 2, "E": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.8, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Le Van Thanh", "position": "Automotive Engineer", "company": "Toyota Vietnam",
         "bio": "Ky su oto, chan doan va sua chua xe hien dai.",
         "skills": ["Automotive Engineering", "Vehicle Diagnostics", "Engine Repair", "Electrical Systems", "Toyota TPS"],
         "yoe": 14, "riasec": {"R": 5, "I": 4, "C": 3, "S": 2, "E": 2, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.7, "extraversion": 3.2, "agreeableness": 3.8, "neuroticism": 1.5}},
    ],
    "production": [
        {"name": "Nguyen Duc Manh", "position": "Production Manager", "company": "Samsung Vietnam",
         "bio": "Quan ly day chuyen san xuat dien tu, lean manufacturing.",
         "skills": ["Production Management", "Lean Manufacturing", "Six Sigma", "Quality Management", "Kaizen"],
         "yoe": 16, "riasec": {"R": 4, "C": 5, "E": 3, "I": 3, "S": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 5.0, "extraversion": 3.8, "agreeableness": 3.5, "neuroticism": 1.5}},
        {"name": "Tran Thi Lan", "position": "Quality Control Engineer", "company": "LG Electronics Vietnam",
         "bio": "Ky su QC, kiem soat chat luong san pham dien tu xuat khau.",
         "skills": ["Quality Control", "ISO 9001", "Statistical Process Control", "Inspection", "Root Cause Analysis"],
         "yoe": 11, "riasec": {"C": 5, "R": 4, "I": 4, "S": 2, "E": 2, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 5.0, "extraversion": 2.8, "agreeableness": 4.0, "neuroticism": 1.5}},
        {"name": "Vo Thanh Nam", "position": "Industrial Engineer", "company": "Piaggio Vietnam",
         "bio": "Ky su cong nghiep, toi uu hoa quy trinh san xuat xe may.",
         "skills": ["Industrial Engineering", "Process Optimization", "Work Study", "Simulation", "Layout Design"],
         "yoe": 13, "riasec": {"R": 4, "I": 5, "C": 4, "E": 2, "S": 2, "A": 2},
         "big5": {"openness": 4.0, "conscientiousness": 4.7, "extraversion": 3.0, "agreeableness": 3.8, "neuroticism": 1.5}},
    ],
    "transportation": [
        {"name": "Nguyen Minh Hung", "position": "Logistics Manager", "company": "DHL Vietnam",
         "bio": "Quan ly chuoi cung ung va van tai quoc te.",
         "skills": ["Supply Chain Management", "Logistics", "Freight Management", "Customs", "Warehouse"],
         "yoe": 16, "riasec": {"C": 4, "E": 4, "R": 3, "S": 3, "I": 3, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.7, "extraversion": 4.0, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Pham Thi Ngoc Tuyen", "position": "Aviation Operations Manager", "company": "Vietnam Airlines",
         "bio": "Quan ly van hanh hang khong, an toan bay.",
         "skills": ["Aviation Operations", "Safety Management System", "Airport Operations", "Flight Planning", "ICAO"],
         "yoe": 15, "riasec": {"R": 4, "C": 5, "I": 3, "E": 3, "S": 3, "A": 2},
         "big5": {"openness": 3.8, "conscientiousness": 4.9, "extraversion": 3.8, "agreeableness": 3.8, "neuroticism": 1.5}},
        {"name": "Le Van Binh", "position": "Fleet Manager", "company": "Grab Vietnam",
         "bio": "Quan ly doi xe, toi uu van hanh doi xe thuong mai.",
         "skills": ["Fleet Management", "Route Optimization", "GPS Tracking", "Vehicle Maintenance", "Driver Training"],
         "yoe": 12, "riasec": {"R": 4, "C": 4, "E": 3, "S": 3, "I": 3, "A": 2},
         "big5": {"openness": 3.5, "conscientiousness": 4.7, "extraversion": 4.0, "agreeableness": 4.0, "neuroticism": 1.5}},
    ],
}

def seed():
    db = SessionLocal()
    created = 0
    skipped = 0
    try:
        for group_slug, mentors in MENTORS.items():
            for i, m in enumerate(mentors):
                email = f"mentor.{group_slug.replace('-','_')}_{i+1}@careerai.demo"
                # Check if user exists
                existing_user = db.query(User).filter(User.email == email).first()
                if existing_user:
                    # Check if mentor profile exists
                    existing_mentor = db.query(MentorProfile).filter(MentorProfile.user_id == existing_user.id).first()
                    if existing_mentor:
                        skipped += 1
                        continue
                    user = existing_user
                else:
                    user = User(
                        email=email,
                        password_hash=DEMO_PASSWORD,
                        full_name=m["name"],
                        role="user",
                    )
                    db.add(user)
                    db.flush()

                mentor = MentorProfile(
                    user_id=user.id,
                    full_name=m["name"],
                    current_position=m["position"],
                    company=m.get("company", "Demo Company"),
                    bio=m.get("bio", ""),
                    expertise_areas=m["skills"],
                    experience_years=m["yoe"],
                    available_hours_per_week=3,
                    preferred_communication=["video", "chat"],
                    max_mentees=5,
                    riasec_scores=m["riasec"],
                    big_five_scores=m["big5"],
                    is_active=True,
                )
                db.add(mentor)
                created += 1

        db.commit()
        print(f"Done: {created} mentors created, {skipped} skipped (already exist)")
    except Exception as e:
        db.rollback()
        import traceback; traceback.print_exc()
        print(f"Error: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
