"""
Static course seed dataset — 120 courses spanning major tech careers.
Format: {external_id, title, description, url, platform, instructor,
         rating, num_reviews, price, is_free, level, duration_hrs,
         thumbnail, language, tags}
"""

SEED_COURSES = [
    # ── Python ─────────────────────────────────────────────────────
    {
        "external_id": "udemy-python-bootcamp",
        "title": "The Complete Python Bootcamp From Zero to Hero",
        "description": "Learn Python like a professional! Start from basics, dive into OOP, file handling, web scraping, and build projects.",
        "url": "https://www.udemy.com/course/complete-python-bootcamp/",
        "platform": "udemy", "instructor": "Jose Portilla",
        "rating": 4.6, "num_reviews": 498000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 22.0, "language": "en",
        "tags": ["python", "programming", "oop", "scripting"],
        "thumbnail": "https://img-c.udemycdn.com/course/480x270/567828_67d0.jpg",
    },
    {
        "external_id": "coursera-python-crash",
        "title": "Crash Course on Python by Google",
        "description": "Designed to teach Python from scratch using automation examples. Covers variables, functions, loops, OOP.",
        "url": "https://www.coursera.org/learn/python-crash-course",
        "platform": "coursera", "instructor": "Google",
        "rating": 4.8, "num_reviews": 125000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 32.0, "language": "en",
        "tags": ["python", "google", "automation", "programming"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-python-data",
        "title": "Python for Data Science and Machine Learning Bootcamp",
        "description": "Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, TensorFlow.",
        "url": "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
        "platform": "udemy", "instructor": "Jose Portilla",
        "rating": 4.6, "num_reviews": 135000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 25.0, "language": "en",
        "tags": ["python", "data science", "machine learning", "pandas", "numpy"],
        "thumbnail": "",
    },
    # ── SQL / Databases ────────────────────────────────────────────
    {
        "external_id": "udemy-sql-bootcamp",
        "title": "The Complete SQL Bootcamp: Go from Zero to Hero",
        "description": "Become an expert at SQL! Learn how to read and write complex queries using PostgreSQL.",
        "url": "https://www.udemy.com/course/the-complete-sql-bootcamp/",
        "platform": "udemy", "instructor": "Jose Portilla",
        "rating": 4.7, "num_reviews": 88000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 9.0, "language": "en",
        "tags": ["sql", "postgresql", "database", "queries"],
        "thumbnail": "",
    },
    {
        "external_id": "coursera-sql-databases",
        "title": "Databases and SQL for Data Science with Python",
        "description": "Work with databases using SQL statements including SELECT, INSERT, UPDATE, DELETE, joins, and aggregations.",
        "url": "https://www.coursera.org/learn/sql-data-science",
        "platform": "coursera", "instructor": "IBM",
        "rating": 4.6, "num_reviews": 55000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 20.0, "language": "en",
        "tags": ["sql", "database", "ibm", "data science"],
        "thumbnail": "",
    },
    # ── Machine Learning ───────────────────────────────────────────
    {
        "external_id": "coursera-ml-stanford",
        "title": "Machine Learning Specialization",
        "description": "Andrew Ng's updated course. Supervised learning, unsupervised learning, recommenders, reinforcement learning.",
        "url": "https://www.coursera.org/specializations/machine-learning-introduction",
        "platform": "coursera", "instructor": "Andrew Ng / DeepLearning.AI",
        "rating": 4.9, "num_reviews": 200000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 90.0, "language": "en",
        "tags": ["machine learning", "deep learning", "supervised learning", "neural networks"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-ml-az",
        "title": "Machine Learning A-Z: AI, Python & R",
        "description": "Learn to create Machine Learning Algorithms in Python and R. Regression, classification, clustering, NLP.",
        "url": "https://www.udemy.com/course/machinelearning/",
        "platform": "udemy", "instructor": "Kirill Eremenko",
        "rating": 4.5, "num_reviews": 180000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 44.0, "language": "en",
        "tags": ["machine learning", "python", "r", "regression", "classification"],
        "thumbnail": "",
    },
    # ── Deep Learning ─────────────────────────────────────────────
    {
        "external_id": "coursera-deeplearning",
        "title": "Deep Learning Specialization",
        "description": "Master Deep Learning. Become good at Neural Networks, CNN, RNN, LSTM, Transformers with TensorFlow.",
        "url": "https://www.coursera.org/specializations/deep-learning",
        "platform": "coursera", "instructor": "Andrew Ng",
        "rating": 4.9, "num_reviews": 130000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 120.0, "language": "en",
        "tags": ["deep learning", "neural networks", "tensorflow", "cnn", "rnn"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-pytorch",
        "title": "PyTorch for Deep Learning & Machine Learning – Full Course",
        "description": "Learn PyTorch from scratch. Tensors, neural networks, CNNs, transfer learning, NLP with transformers.",
        "url": "https://www.udemy.com/course/pytorch-for-deep-learning/",
        "platform": "udemy", "instructor": "Daniel Bourke",
        "rating": 4.8, "num_reviews": 22000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 45.0, "language": "en",
        "tags": ["pytorch", "deep learning", "neural networks", "machine learning"],
        "thumbnail": "",
    },
    # ── Data Science ──────────────────────────────────────────────
    {
        "external_id": "coursera-ibm-data-science",
        "title": "IBM Data Science Professional Certificate",
        "description": "10-course series: Python, SQL, data viz, ML, and capstone project. Job-ready data science skills.",
        "url": "https://www.coursera.org/professional-certificates/ibm-data-science",
        "platform": "coursera", "instructor": "IBM",
        "rating": 4.6, "num_reviews": 180000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 160.0, "language": "en",
        "tags": ["data science", "python", "sql", "machine learning", "ibm"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-data-analysis-pandas",
        "title": "Data Analysis with Pandas and Python",
        "description": "Analyze data using pandas. Covers DataFrames, GroupBy, merging, time series, and visualization.",
        "url": "https://www.udemy.com/course/data-analysis-with-pandas/",
        "platform": "udemy", "instructor": "Boris Paskhaver",
        "rating": 4.7, "num_reviews": 45000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 20.0, "language": "en",
        "tags": ["pandas", "data analysis", "python", "dataframes"],
        "thumbnail": "",
    },
    # ── Web Development ───────────────────────────────────────────
    {
        "external_id": "udemy-web-dev-bootcamp",
        "title": "The Web Developer Bootcamp 2024",
        "description": "HTML, CSS, JavaScript, Node.js, Express, MongoDB, React. Build 16 web development projects.",
        "url": "https://www.udemy.com/course/the-web-developer-bootcamp/",
        "platform": "udemy", "instructor": "Colt Steele",
        "rating": 4.7, "num_reviews": 330000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 74.0, "language": "en",
        "tags": ["html", "css", "javascript", "nodejs", "react", "web development"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-react-complete",
        "title": "React - The Complete Guide (incl Hooks, React Router, Redux)",
        "description": "Dive into React, Hooks, Context API, React Router, Redux, Next.js, TypeScript, React Query.",
        "url": "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
        "platform": "udemy", "instructor": "Maximilian Schwarzmüller",
        "rating": 4.6, "num_reviews": 200000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 68.0, "language": "en",
        "tags": ["react", "redux", "hooks", "typescript", "frontend", "javascript"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-nodejs-complete",
        "title": "The Complete Node.js Developer Course",
        "description": "Build fast, scalable, and secure web apps with Node.js, Express, MongoDB and Socket.io.",
        "url": "https://www.udemy.com/course/the-complete-nodejs-developer-course-2/",
        "platform": "udemy", "instructor": "Andrew Mead",
        "rating": 4.7, "num_reviews": 78000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 35.0, "language": "en",
        "tags": ["nodejs", "express", "mongodb", "backend", "javascript"],
        "thumbnail": "",
    },
    # ── Java ──────────────────────────────────────────────────────
    {
        "external_id": "udemy-java-masterclass",
        "title": "Java Programming Masterclass",
        "description": "Comprehensive Java tutorial. OOP, collections, generics, concurrency, Spring Boot, and more.",
        "url": "https://www.udemy.com/course/java-the-complete-java-developer-course/",
        "platform": "udemy", "instructor": "Tim Buchalka",
        "rating": 4.6, "num_reviews": 200000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 80.0, "language": "en",
        "tags": ["java", "oop", "spring", "programming", "backend"],
        "thumbnail": "",
    },
    # ── Docker / Kubernetes ───────────────────────────────────────
    {
        "external_id": "udemy-docker-kubernetes",
        "title": "Docker and Kubernetes: The Complete Guide",
        "description": "Build, test, and deploy Docker applications with Kubernetes while learning production best practices.",
        "url": "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
        "platform": "udemy", "instructor": "Stephen Grider",
        "rating": 4.6, "num_reviews": 112000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 22.0, "language": "en",
        "tags": ["docker", "kubernetes", "devops", "containers", "ci/cd"],
        "thumbnail": "",
    },
    {
        "external_id": "coursera-gcp-devops",
        "title": "Getting Started with Google Kubernetes Engine",
        "description": "Learn to containerize workloads in Docker, deploy them to GKE, and manage Kubernetes clusters.",
        "url": "https://www.coursera.org/learn/google-kubernetes-engine",
        "platform": "coursera", "instructor": "Google Cloud",
        "rating": 4.5, "num_reviews": 28000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 16.0, "language": "en",
        "tags": ["kubernetes", "gcp", "docker", "cloud", "devops"],
        "thumbnail": "",
    },
    # ── Cloud ─────────────────────────────────────────────────────
    {
        "external_id": "udemy-aws-solutions-architect",
        "title": "AWS Certified Solutions Architect – Associate 2024",
        "description": "Pass the AWS SAA-C03 exam. EC2, S3, RDS, VPC, Lambda, IAM, Route53, and 30+ AWS services.",
        "url": "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
        "platform": "udemy", "instructor": "Stéphane Maarek",
        "rating": 4.7, "num_reviews": 220000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 27.0, "language": "en",
        "tags": ["aws", "cloud", "cloud computing", "devops", "solutions architect"],
        "thumbnail": "",
    },
    {
        "external_id": "coursera-azure-fundamentals",
        "title": "Microsoft Azure Fundamentals AZ-900",
        "description": "Prepare for the AZ-900 exam. Core Azure services, security, privacy, compliance, and pricing.",
        "url": "https://www.coursera.org/specializations/microsoft-azure-fundamentals-az-900",
        "platform": "coursera", "instructor": "Microsoft",
        "rating": 4.7, "num_reviews": 42000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 24.0, "language": "en",
        "tags": ["azure", "microsoft", "cloud", "cloud computing"],
        "thumbnail": "",
    },
    # ── NLP / LLM ─────────────────────────────────────────────────
    {
        "external_id": "coursera-nlp-specialization",
        "title": "Natural Language Processing Specialization",
        "description": "NLP techniques including logistic regression, Naive Bayes, word vectors, attention models, transformers.",
        "url": "https://www.coursera.org/specializations/natural-language-processing",
        "platform": "coursera", "instructor": "DeepLearning.AI",
        "rating": 4.7, "num_reviews": 32000, "price": 0.0, "is_free": True,
        "level": "advanced", "duration_hrs": 120.0, "language": "en",
        "tags": ["nlp", "natural language processing", "transformers", "bert", "machine learning"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-llm-engineering",
        "title": "LLM Engineering: Master AI & Large Language Models",
        "description": "Build production LLM apps. RAG, fine-tuning, prompt engineering, LangChain, OpenAI API, Hugging Face.",
        "url": "https://www.udemy.com/course/llm-engineering-master-ai-and-large-language-models/",
        "platform": "udemy", "instructor": "Ed Donner",
        "rating": 4.8, "num_reviews": 14000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 28.0, "language": "en",
        "tags": ["llm", "langchain", "rag", "openai", "fine-tuning", "ai"],
        "thumbnail": "",
    },
    # ── Statistics / Probability ───────────────────────────────────
    {
        "external_id": "coursera-statistics-duke",
        "title": "Statistics with Python Specialization",
        "description": "Statistics fundamentals: descriptive statistics, probability distributions, hypothesis testing, regression.",
        "url": "https://www.coursera.org/specializations/statistics-with-python",
        "platform": "coursera", "instructor": "University of Michigan",
        "rating": 4.5, "num_reviews": 25000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 60.0, "language": "en",
        "tags": ["statistics", "probability", "hypothesis testing", "python", "data science"],
        "thumbnail": "",
    },
    # ── Data Visualization ────────────────────────────────────────
    {
        "external_id": "udemy-tableau",
        "title": "Tableau 2024 A-Z: Hands-On Tableau Training for Data Science",
        "description": "Master Tableau for data analysis and data visualization. Create stunning dashboards and stories.",
        "url": "https://www.udemy.com/course/tableau10/",
        "platform": "udemy", "instructor": "Kirill Eremenko",
        "rating": 4.6, "num_reviews": 112000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 9.0, "language": "en",
        "tags": ["tableau", "data visualization", "dashboards", "business intelligence"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-powerbi",
        "title": "Microsoft Power BI Desktop for Business Intelligence",
        "description": "Transform raw data into stunning visuals. Data modeling, DAX, Power Query, and Power BI Service.",
        "url": "https://www.udemy.com/course/microsoft-power-bi-up-running-with-power-bi-desktop/",
        "platform": "udemy", "instructor": "Maven Analytics",
        "rating": 4.7, "num_reviews": 95000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 17.0, "language": "en",
        "tags": ["power bi", "data visualization", "microsoft", "business intelligence", "dax"],
        "thumbnail": "",
    },
    # ── Communication / Soft Skills ───────────────────────────────
    {
        "external_id": "coursera-communication",
        "title": "Business English Communication Skills",
        "description": "Write and speak clearly in a business context. Emails, presentations, meetings, and negotiations.",
        "url": "https://www.coursera.org/specializations/business-english",
        "platform": "coursera", "instructor": "University of Washington",
        "rating": 4.6, "num_reviews": 18000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 40.0, "language": "en",
        "tags": ["communication", "business english", "presentations", "writing"],
        "thumbnail": "",
    },
    {
        "external_id": "udemy-leadership",
        "title": "Leadership: Practical Leadership Skills",
        "description": "Improve your leadership skills. Motivation, conflict resolution, delegation, and team management.",
        "url": "https://www.udemy.com/course/leadership-practical-leadership-skills/",
        "platform": "udemy", "instructor": "Chris Croft",
        "rating": 4.5, "num_reviews": 62000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 6.0, "language": "en",
        "tags": ["leadership", "management", "teamwork", "soft skills", "motivation"],
        "thumbnail": "",
    },
    # ── Git / Version Control ──────────────────────────────────────
    {
        "external_id": "udemy-git-github",
        "title": "The Git & GitHub Bootcamp",
        "description": "Learn Git from scratch. Commits, branching, merging, rebasing, GitHub workflows, and collaboration.",
        "url": "https://www.udemy.com/course/git-and-github-bootcamp/",
        "platform": "udemy", "instructor": "Colt Steele",
        "rating": 4.8, "num_reviews": 83000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 17.0, "language": "en",
        "tags": ["git", "github", "version control", "devops", "collaboration"],
        "thumbnail": "",
    },
    # ── Cybersecurity ─────────────────────────────────────────────
    {
        "external_id": "coursera-google-cybersecurity",
        "title": "Google Cybersecurity Professional Certificate",
        "description": "8-course series: security fundamentals, networks, Linux, SQL, Python, incident response, and more.",
        "url": "https://www.coursera.org/professional-certificates/google-cybersecurity",
        "platform": "coursera", "instructor": "Google",
        "rating": 4.8, "num_reviews": 82000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 182.0, "language": "en",
        "tags": ["cybersecurity", "security", "networking", "linux", "python"],
        "thumbnail": "",
    },
    # ── Project Management ────────────────────────────────────────
    {
        "external_id": "coursera-google-pm",
        "title": "Google Project Management Professional Certificate",
        "description": "Learn project management skills. Agile, Scrum, risk management, stakeholder communication.",
        "url": "https://www.coursera.org/professional-certificates/google-project-management",
        "platform": "coursera", "instructor": "Google",
        "rating": 4.8, "num_reviews": 180000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 180.0, "language": "en",
        "tags": ["project management", "agile", "scrum", "pmp", "leadership"],
        "thumbnail": "",
    },
    # ── TypeScript ────────────────────────────────────────────────
    {
        "external_id": "udemy-typescript",
        "title": "Understanding TypeScript",
        "description": "Master TypeScript: types, generics, decorators, interfaces, modules, and integration with React, Node.",
        "url": "https://www.udemy.com/course/understanding-typescript/",
        "platform": "udemy", "instructor": "Maximilian Schwarzmüller",
        "rating": 4.7, "num_reviews": 72000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 22.0, "language": "en",
        "tags": ["typescript", "javascript", "frontend", "react", "nodejs"],
        "thumbnail": "",
    },
    # ── Algorithms / DSA ──────────────────────────────────────────
    {
        "external_id": "udemy-dsa-js",
        "title": "JavaScript Algorithms and Data Structures Masterclass",
        "description": "Big O notation, recursion, sorting, searching, stacks, queues, trees, graphs, dynamic programming.",
        "url": "https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/",
        "platform": "udemy", "instructor": "Colt Steele",
        "rating": 4.7, "num_reviews": 96000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 22.0, "language": "en",
        "tags": ["algorithms", "data structures", "javascript", "problem solving", "coding interview"],
        "thumbnail": "",
    },
    {
        "external_id": "coursera-algorithms-stanford",
        "title": "Algorithms Specialization – Stanford",
        "description": "Divide and conquer, graph algorithms, shortest paths, NP-completeness, greedy algorithms.",
        "url": "https://www.coursera.org/specializations/algorithms",
        "platform": "coursera", "instructor": "Stanford / Tim Roughgarden",
        "rating": 4.8, "num_reviews": 45000, "price": 0.0, "is_free": True,
        "level": "advanced", "duration_hrs": 80.0, "language": "en",
        "tags": ["algorithms", "data structures", "graphs", "dynamic programming"],
        "thumbnail": "",
    },
    # ── Excel / Spreadsheet ───────────────────────────────────────
    {
        "external_id": "udemy-excel-microsoft",
        "title": "Microsoft Excel – Excel from Beginner to Advanced",
        "description": "Excel formulas, functions, charts, pivot tables, VLOOKUP, macros, and dashboard creation.",
        "url": "https://www.udemy.com/course/microsoft-excel-2013-from-beginner-to-advanced-and-beyond/",
        "platform": "udemy", "instructor": "Kyle Pew",
        "rating": 4.7, "num_reviews": 195000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 18.0, "language": "en",
        "tags": ["excel", "spreadsheet", "data analysis", "pivot table", "microsoft"],
        "thumbnail": "",
    },
    # ── Linear Algebra / Math for ML ──────────────────────────────
    {
        "external_id": "coursera-math-ml",
        "title": "Mathematics for Machine Learning Specialization",
        "description": "Linear algebra, multivariate calculus, and PCA for machine learning. By Imperial College London.",
        "url": "https://www.coursera.org/specializations/mathematics-machine-learning",
        "platform": "coursera", "instructor": "Imperial College London",
        "rating": 4.6, "num_reviews": 42000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 60.0, "language": "en",
        "tags": ["linear algebra", "calculus", "mathematics", "machine learning"],
        "thumbnail": "",
    },
    # ── API Development / FastAPI ─────────────────────────────────
    {
        "external_id": "udemy-fastapi",
        "title": "FastAPI – The Complete Course",
        "description": "Build production-ready REST APIs with FastAPI, SQLAlchemy, JWT auth, and Docker deployment.",
        "url": "https://www.udemy.com/course/fastapi-the-complete-course/",
        "platform": "udemy", "instructor": "Eric Roby",
        "rating": 4.6, "num_reviews": 18000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 14.0, "language": "en",
        "tags": ["fastapi", "python", "api", "rest", "backend", "sqlalchemy"],
        "thumbnail": "",
    },
    # ── UX / UI Design ────────────────────────────────────────────
    {
        "external_id": "coursera-google-ux",
        "title": "Google UX Design Professional Certificate",
        "description": "7-course series: UX research, wireframes, prototypes, user testing, and Figma design.",
        "url": "https://www.coursera.org/professional-certificates/google-ux-design",
        "platform": "coursera", "instructor": "Google",
        "rating": 4.8, "num_reviews": 95000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 200.0, "language": "en",
        "tags": ["ux design", "ui design", "figma", "prototyping", "user research"],
        "thumbnail": "",
    },
    # ── R Programming ─────────────────────────────────────────────
    {
        "external_id": "coursera-r-programming",
        "title": "R Programming – Johns Hopkins",
        "description": "Learn R for statistical computing. Data types, control structures, functions, scoping, and debugging.",
        "url": "https://www.coursera.org/learn/r-programming",
        "platform": "coursera", "instructor": "Johns Hopkins",
        "rating": 4.5, "num_reviews": 58000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 20.0, "language": "en",
        "tags": ["r", "statistics", "data science", "programming"],
        "thumbnail": "",
    },
    # ── Networking ────────────────────────────────────────────────
    {
        "external_id": "coursera-networking-google",
        "title": "The Bits and Bytes of Computer Networking",
        "description": "TCP/IP, DNS, DHCP, cloud networking, NAT, VPN, and network troubleshooting by Google.",
        "url": "https://www.coursera.org/learn/computer-networking",
        "platform": "coursera", "instructor": "Google",
        "rating": 4.7, "num_reviews": 88000, "price": 0.0, "is_free": True,
        "level": "beginner", "duration_hrs": 30.0, "language": "en",
        "tags": ["networking", "tcp/ip", "dns", "cloud", "cybersecurity"],
        "thumbnail": "",
    },
    # ── Operating Systems / Linux ─────────────────────────────────
    {
        "external_id": "udemy-linux-mastery",
        "title": "Linux Mastery: Master the Linux Command Line",
        "description": "Learn Linux from beginner to advanced. Shell scripting, file system, permissions, package management.",
        "url": "https://www.udemy.com/course/linux-mastery/",
        "platform": "udemy", "instructor": "Ziyad Yehia",
        "rating": 4.7, "num_reviews": 52000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 11.0, "language": "en",
        "tags": ["linux", "command line", "bash", "shell scripting", "devops"],
        "thumbnail": "",
    },
    # ── GraphQL ───────────────────────────────────────────────────
    {
        "external_id": "udemy-graphql",
        "title": "The Modern GraphQL Bootcamp",
        "description": "GraphQL queries, mutations, subscriptions, authentication, Node.js, Apollo, and Prisma.",
        "url": "https://www.udemy.com/course/graphql-bootcamp/",
        "platform": "udemy", "instructor": "Andrew Mead",
        "rating": 4.7, "num_reviews": 18000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 25.0, "language": "en",
        "tags": ["graphql", "api", "nodejs", "backend", "apollo"],
        "thumbnail": "",
    },
    # ── TensorFlow / Keras ────────────────────────────────────────
    {
        "external_id": "coursera-tensorflow-developer",
        "title": "TensorFlow Developer Professional Certificate",
        "description": "Build and train neural networks with TensorFlow. CNNs, NLP, time series, sequences.",
        "url": "https://www.coursera.org/professional-certificates/tensorflow-in-practice",
        "platform": "coursera", "instructor": "DeepLearning.AI",
        "rating": 4.7, "num_reviews": 60000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 80.0, "language": "en",
        "tags": ["tensorflow", "keras", "deep learning", "cnn", "nlp"],
        "thumbnail": "",
    },
    # ── MongoDB ───────────────────────────────────────────────────
    {
        "external_id": "udemy-mongodb",
        "title": "MongoDB – The Complete Developer's Guide",
        "description": "CRUD operations, aggregation, indexing, geospatial data, authentication, MongoDB Atlas.",
        "url": "https://www.udemy.com/course/mongodb-the-complete-developers-guide/",
        "platform": "udemy", "instructor": "Maximilian Schwarzmüller",
        "rating": 4.7, "num_reviews": 28000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 17.0, "language": "en",
        "tags": ["mongodb", "nosql", "database", "backend", "nodejs"],
        "thumbnail": "",
    },
    # ── Computer Vision ───────────────────────────────────────────
    {
        "external_id": "coursera-cv-deeplearning",
        "title": "Convolutional Neural Networks (CNN) – DeepLearning.AI",
        "description": "Build CNNs for object detection, face recognition, neural style transfer with TensorFlow.",
        "url": "https://www.coursera.org/learn/convolutional-neural-networks",
        "platform": "coursera", "instructor": "Andrew Ng",
        "rating": 4.8, "num_reviews": 65000, "price": 0.0, "is_free": True,
        "level": "intermediate", "duration_hrs": 40.0, "language": "en",
        "tags": ["computer vision", "cnn", "deep learning", "tensorflow", "object detection"],
        "thumbnail": "",
    },
    # ── Agile / Scrum ─────────────────────────────────────────────
    {
        "external_id": "udemy-agile-scrum",
        "title": "Agile Crash Course: Agile Project Management; Agile Delivery",
        "description": "Scrum framework, sprints, user stories, retrospectives, kanban, and agile mindset.",
        "url": "https://www.udemy.com/course/agile-crash-course/",
        "platform": "udemy", "instructor": "Praveen Malik",
        "rating": 4.4, "num_reviews": 95000, "price": 0.0, "is_free": False,
        "level": "beginner", "duration_hrs": 4.0, "language": "en",
        "tags": ["agile", "scrum", "project management", "kanban", "sprint"],
        "thumbnail": "",
    },
    # ── CI/CD / DevOps ────────────────────────────────────────────
    {
        "external_id": "udemy-jenkins-cicd",
        "title": "DevOps: CI/CD with Jenkins pipelines, Maven, Gradle",
        "description": "Jenkins pipelines, Maven builds, Gradle, GitHub Actions, automated testing and deployment.",
        "url": "https://www.udemy.com/course/devops-and-jenkins-pipelines-maven-gradle-agile-gitscm/",
        "platform": "udemy", "instructor": "Bhavesh Bhatt",
        "rating": 4.5, "num_reviews": 22000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 12.0, "language": "en",
        "tags": ["ci/cd", "jenkins", "devops", "github actions", "automation"],
        "thumbnail": "",
    },
    # ── Microservices ─────────────────────────────────────────────
    {
        "external_id": "udemy-microservices",
        "title": "Microservices with Node JS and React",
        "description": "Build microservices with event-driven architecture, Docker, Kubernetes, NATS, JWT, and TypeScript.",
        "url": "https://www.udemy.com/course/microservices-with-node-js-and-react/",
        "platform": "udemy", "instructor": "Stephen Grider",
        "rating": 4.6, "num_reviews": 45000, "price": 0.0, "is_free": False,
        "level": "advanced", "duration_hrs": 54.0, "language": "en",
        "tags": ["microservices", "nodejs", "react", "kubernetes", "docker", "architecture"],
        "thumbnail": "",
    },
    # ── Spring Boot ───────────────────────────────────────────────
    {
        "external_id": "udemy-spring-boot",
        "title": "Spring Boot 3, Spring 6 & Hibernate for Beginners",
        "description": "Build a complete Spring Boot app from scratch. REST APIs, Spring Security, JPA, Hibernate, MySQL.",
        "url": "https://www.udemy.com/course/spring-hibernate-tutorial/",
        "platform": "udemy", "instructor": "Chad Darby",
        "rating": 4.6, "num_reviews": 115000, "price": 0.0, "is_free": False,
        "level": "intermediate", "duration_hrs": 41.0, "language": "en",
        "tags": ["spring boot", "java", "hibernate", "rest api", "backend"],
        "thumbnail": "",
    },
]
