-- ============================================================
-- Schema: core.essay_prompts (bilingual: VI + EN)
-- Generated by translate_essay_prompts.py
-- Columns: title_en, title_vi (adjacent) | prompt_text_en, prompt_text_vi (adjacent)
-- ============================================================

-- DROP TABLE IF EXISTS core.essay_prompts;

CREATE TABLE IF NOT EXISTS core.essay_prompts
(
    id              bigint NOT NULL DEFAULT nextval('core.essay_prompts_id_seq'::regclass),
    title_en        text   NOT NULL,
    title_vi        text   NOT NULL,
    prompt_text_en  text   NOT NULL,
    prompt_text_vi  text   NOT NULL,
    created_at      timestamp with time zone DEFAULT now(),
    CONSTRAINT essay_prompts_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS core.essay_prompts OWNER TO postgres;

-- Unique constraint on Vietnamese title (natural key)
ALTER TABLE core.essay_prompts
    ADD CONSTRAINT IF NOT EXISTS essay_prompts_title_vi_key UNIQUE (title_vi);

-- ── SEED DATA (50 rows) ──────────────────────────────────────────────────

TRUNCATE core.essay_prompts RESTART IDENTITY CASCADE;

INSERT INTO core.essay_prompts (title_en, title_vi, prompt_text_en, prompt_text_vi) VALUES
  ('Ideal career', 'Nghề nghiệp lý tưởng', 'Please describe your ideal future career.What skills and personal qualities make you suitable for that job, and why does it appeal to you?', 'Hãy mô tả nghề nghiệp lý tưởng của bạn trong tương lai. Những kỹ năng và phẩm chất cá nhân nào khiến bạn phù hợp với công việc đó, và tại sao nó thu hút bạn?'),
  ('Goals for the next 5 years', 'Mục tiêu 5 năm tới', 'What do you want to achieve in your career in 5 years?Describe your specific plan and the steps you will take to achieve that goal.', 'Bạn muốn đạt được điều gì trong sự nghiệp sau 5 năm nữa? Hãy mô tả kế hoạch cụ thể và những bước bạn sẽ thực hiện để đạt được mục tiêu đó.'),
  ('The meaning of success', 'Ý nghĩa của thành công', 'What does success mean to you?Please share your views and what factors you consider most important to achieve it.', 'Thành công có ý nghĩa gì với bạn? Hãy chia sẻ quan điểm của bạn và những yếu tố nào bạn cho là quan trọng nhất để đạt được nó.'),
  ('Source of work motivation', 'Nguồn động lực làm việc', 'What motivates you to work hard every day?Describe the main sources of motivation in your life and work.', 'Điều gì thúc đẩy bạn làm việc chăm chỉ mỗi ngày? Hãy mô tả những nguồn động lực chính trong cuộc sống và công việc của bạn.'),
  ('Dream since childhood', 'Ước mơ từ thuở nhỏ', 'When you were a child, what did you dream of becoming?Has that dream changed and why?How does it influence your current choices?', 'Khi còn nhỏ, bạn từng mơ ước trở thành gì? Ước mơ đó có thay đổi không và tại sao? Nó ảnh hưởng như thế nào đến lựa chọn hiện tại của bạn?'),
  ('Ideal working environment', 'Môi trường làm việc lý tưởng', 'Describe the work environment in which you feel most comfortable and productive.Do you like working alone or in a group?Why?', 'Mô tả môi trường làm việc mà bạn cảm thấy thoải mái và hiệu quả nhất. Bạn thích làm việc một mình hay theo nhóm? Tại sao?'),
  ('Skills you want to develop', 'Kỹ năng muốn phát triển', 'What skills do you want to develop most in the near future?Why is that skill important to you and what are your plans to improve it?', 'Bạn muốn phát triển kỹ năng gì nhất trong thời gian tới? Tại sao kỹ năng đó quan trọng với bạn và bạn có kế hoạch gì để cải thiện nó?'),
  ('Contribute to society', 'Đóng góp cho xã hội', 'What do you want to contribute to society through your work?Share about the positive impact you hope to create.', 'Bạn muốn đóng góp gì cho xã hội thông qua công việc của mình? Hãy chia sẻ về tác động tích cực mà bạn mong muốn tạo ra.'),
  ('Work and life balance', 'Cân bằng công việc và cuộc sống', 'How do you plan to balance your career and personal life?What is most important to you in maintaining this balance?', 'Làm thế nào bạn định cân bằng giữa sự nghiệp và cuộc sống cá nhân? Điều gì quan trọng nhất với bạn trong việc duy trì sự cân bằng này?'),
  ('If I could choose my career again', 'Nếu được chọn lại nghề nghiệp', 'If you had the opportunity to completely change your career, what would you choose to do?Why does that option appeal to you and what challenges are you willing to face?', 'Nếu có cơ hội thay đổi hoàn toàn nghề nghiệp, bạn sẽ chọn làm gì? Tại sao lựa chọn đó hấp dẫn bạn và bạn sẵn sàng đối mặt với những thách thức gì?'),
  ('Overcome great challenges', 'Vượt qua thử thách lớn', 'Tell me about a time when you faced a difficult challenge.How did you overcome it and what did you learn about yourself from the experience?', 'Hãy kể về một lần bạn đối mặt với thử thách khó khăn. Bạn đã vượt qua nó như thế nào và học được gì về bản thân từ trải nghiệm đó?'),
  ('Failure and lessons', 'Thất bại và bài học', 'What is the biggest failure in your life?What did you learn from it and how did it change you?', 'Thất bại lớn nhất trong cuộc đời bạn là gì? Bạn đã học được gì từ nó và nó thay đổi bạn như thế nào?'),
  ('Pressure management', 'Quản lý áp lực', 'When you encounter great pressure in study or work, how do you usually react?What methods help you manage stress effectively?', 'Khi gặp áp lực lớn trong học tập hoặc công việc, bạn thường phản ứng như thế nào? Những phương pháp nào giúp bạn quản lý stress hiệu quả?'),
  ('The hardest decision', 'Quyết định khó khăn nhất', 'Describe a difficult decision you had to make.What factors did you consider and how do you feel about that decision now?', 'Hãy mô tả một quyết định khó khăn mà bạn đã phải đưa ra. Bạn đã cân nhắc những yếu tố gì và cảm thấy thế nào về quyết định đó hiện tại?'),
  ('Resolve conflicts', 'Giải quyết xung đột', 'Tell about a time you had a conflict with someone.How did you handle that situation and what did you learn from the experience?', 'Kể về một lần bạn có xung đột với ai đó. Bạn đã giải quyết tình huống đó như thế nào và học được gì từ kinh nghiệm này?'),
  ('When you want to give up', 'Khi muốn bỏ cuộc', 'Was there ever a time when you wanted to give up?What helped you keep going and get through that difficult period?', 'Có lúc nào bạn muốn bỏ cuộc không? Điều gì đã giúp bạn tiếp tục và vượt qua giai đoạn khó khăn đó?'),
  ('Adapt to unexpected changes', 'Thích ứng với thay đổi bất ngờ', 'How do you adapt to unexpected changes?Please share a specific example of how you cope with change.', 'Bạn thích ứng với những thay đổi bất ngờ như thế nào? Hãy chia sẻ một ví dụ cụ thể về cách bạn đối phó với sự thay đổi.'),
  ('Learn from mistakes', 'Học hỏi từ sai lầm', 'Tell me about a mistake you made and how you learned from it.How did that mistake help you become better?', 'Hãy kể về một sai lầm mà bạn đã mắc phải và cách bạn học hỏi từ nó. Sai lầm đó đã giúp bạn trở nên tốt hơn như thế nào?'),
  ('Overcome fear', 'Vượt qua nỗi sợ hãi', 'Have you ever overcome any of your fears?Describe that experience and how you felt after going through it.', 'Bạn đã từng vượt qua nỗi sợ hãi nào của mình chưa? Hãy mô tả trải nghiệm đó và cảm giác của bạn sau khi vượt qua nó.'),
  ('Seek support', 'Tìm kiếm sự hỗ trợ', 'When you encounter difficulties, where do you usually look for support?What is the role of family and friends in helping you overcome challenges?', 'Khi gặp khó khăn, bạn thường tìm kiếm sự hỗ trợ từ đâu? Vai trò của gia đình, bạn bè trong việc giúp bạn vượt qua thử thách là gì?'),
  ('Favorite creative project', 'Dự án sáng tạo yêu thích', 'Describe a creative project you have worked on or would like to work on.What inspires you and how did you approach it?', 'Hãy mô tả một dự án sáng tạo mà bạn đã thực hiện hoặc muốn thực hiện. Điều gì truyền cảm hứng cho bạn và bạn đã tiếp cận nó như thế nào?'),
  ('Solve problems in new ways', 'Giải quyết vấn đề theo cách mới', 'Tell about a time when you solved a problem in a creative, unconventional way.Where did that idea come from and what was the result?', 'Kể về một lần bạn giải quyết vấn đề theo cách sáng tạo, khác với cách thông thường. Ý tưởng đó đến từ đâu và kết quả như thế nào?'),
  ('Artistic hobbies', 'Sở thích nghệ thuật', 'Do you have any artistic or creative interests?Share about it and how it affects your life and work.', 'Bạn có sở thích nghệ thuật hoặc sáng tạo nào không? Hãy chia sẻ về nó và cách nó ảnh hưởng đến cuộc sống và công việc của bạn.'),
  ('Combine ideas from many fields', 'Kết hợp ý tưởng từ nhiều lĩnh vực', 'Describe a time when you combined ideas from different fields to create something new.How does that process happen?', 'Hãy mô tả một lần bạn kết hợp ý tưởng từ các lĩnh vực khác nhau để tạo ra điều gì đó mới. Quá trình đó diễn ra như thế nào?'),
  ('Experience new culture', 'Trải nghiệm văn hóa mới', 'Tell me about a cultural or artistic experience that changed the way you see the world.How does it affect you?', 'Hãy kể về một trải nghiệm văn hóa hoặc nghệ thuật đã thay đổi cách bạn nhìn nhận thế giới. Nó ảnh hưởng đến bạn như thế nào?'),
  ('Critical thinking', 'Tư duy phản biện', 'Describe a situation in which you questioned a commonly held opinion.How did you approach that problem and what were your conclusions?', 'Hãy mô tả một tình huống bạn đã đặt câu hỏi về một quan điểm phổ biến. Bạn đã tiếp cận vấn đề đó như thế nào và kết luận của bạn là gì?'),
  ('Creative business idea', 'Ý tưởng kinh doanh sáng tạo', 'If you could create a completely new product or service, what would it be?Describe your idea and why you think it has value.', 'Nếu bạn có thể tạo ra một sản phẩm hoặc dịch vụ hoàn toàn mới, đó sẽ là gì? Hãy mô tả ý tưởng và lý do bạn nghĩ nó có giá trị.'),
  ('Learn through experience', 'Học hỏi qua trải nghiệm', 'Describe an informal learning experience (outside of school) that had a major impact on you.What did you learn and how did it change you?', 'Hãy mô tả một trải nghiệm học hỏi không chính thức (ngoài trường lớp) đã có tác động lớn đến bạn. Bạn học được gì và nó thay đổi bạn như thế nào?'),
  ('Lead the group', 'Dẫn dắt nhóm', 'Tell me about a time you led a group.How did you approach your leadership role and what did you learn from the experience?', 'Hãy kể về một lần bạn dẫn dắt một nhóm. Bạn đã tiếp cận vai trò lãnh đạo như thế nào và học được gì từ trải nghiệm đó?'),
  ('Work effectively in groups', 'Làm việc nhóm hiệu quả', 'Describe a successful group project in which you participated.What was your role and what challenges did the team overcome?', 'Mô tả một dự án nhóm thành công mà bạn đã tham gia. Vai trò của bạn là gì và nhóm đã vượt qua những thách thức nào?'),
  ('Handling difficult members', 'Xử lý thành viên khó tính', 'Have you ever worked with a team member who was difficult to work with?How did you handle that situation?', 'Bạn đã từng làm việc với một thành viên nhóm khó hợp tác chưa? Bạn đã xử lý tình huống đó như thế nào?'),
  ('Inspire others', 'Truyền cảm hứng cho người khác', 'Tell me about a time when you inspired or motivated someone.What did you do and what was its impact?', 'Hãy kể về một lần bạn truyền cảm hứng hoặc động viên người khác. Bạn đã làm gì và tác động của nó là gì?'),
  ('Assign group work', 'Phân công công việc nhóm', 'When working in groups, how do you usually approach assigning tasks?Please share a specific example.', 'Khi làm việc nhóm, bạn thường tiếp cận việc phân công nhiệm vụ như thế nào? Hãy chia sẻ một ví dụ cụ thể.'),
  ('Receive and give feedback', 'Nhận và đưa ra phản hồi', 'How do you feel when you receive negative feedback?How did you learn to give constructive feedback?', 'Bạn cảm thấy thế nào khi nhận phản hồi tiêu cực? Bạn đã học cách đưa ra phản hồi mang tính xây dựng như thế nào?'),
  ('Decisions within the group', 'Quyết định trong nhóm', 'Describe a situation where your group had to make an important decision under time pressure.How does that process happen?', 'Hãy mô tả một tình huống nhóm bạn phải đưa ra quyết định quan trọng dưới áp lực thời gian. Quá trình đó diễn ra như thế nào?'),
  ('Diversity within the group', 'Đa dạng trong nhóm', 'Have you ever worked in a team with cultural or perspective diversity?How does that affect work?', 'Bạn đã từng làm việc trong một nhóm có sự đa dạng về văn hóa hoặc quan điểm chưa? Điều đó ảnh hưởng đến công việc như thế nào?'),
  ('Long-term study plan', 'Kế hoạch học tập dài hạn', 'Do you have plans for study or professional development in the next 3-5 years?Describe your route and why you chose that direction.', 'Bạn có kế hoạch học tập hoặc phát triển chuyên môn trong 3-5 năm tới không? Hãy mô tả lộ trình và lý do bạn chọn hướng đó.'),
  ('Build a personal brand', 'Xây dựng thương hiệu cá nhân', 'How do you want others to remember you in your career?What are you doing to build your professional image?', 'Bạn muốn người khác nhớ đến bạn như thế nào trong sự nghiệp? Bạn đang làm gì để xây dựng hình ảnh chuyên nghiệp của mình?'),
  ('Future industry trends', 'Xu hướng ngành nghề tương lai', 'How do you think your industry will change in the next 10 years?What are you preparing to adapt to those changes?', 'Bạn nghĩ ngành nghề của mình sẽ thay đổi như thế nào trong 10 năm tới? Bạn đang chuẩn bị gì để thích ứng với những thay đổi đó?'),
  ('Network of professional relationships', 'Mạng lưới quan hệ nghề nghiệp', 'How do you approach building your professional network?Which relationships do you consider most important?', 'Bạn tiếp cận việc xây dựng mạng lưới quan hệ nghề nghiệp như thế nào? Những mối quan hệ nào bạn cho là quan trọng nhất?'),
  ('Learn continuously', 'Học hỏi liên tục', 'In a rapidly changing world, how do you maintain continuous learning?Please share your study methods and habits.', 'Trong thế giới thay đổi nhanh chóng, bạn duy trì việc học hỏi liên tục như thế nào? Hãy chia sẻ phương pháp và thói quen học tập của bạn.'),
  ('Personal financial management', 'Quản lý tài chính cá nhân', 'Do you have a personal financial plan?Please share how you approach financial management to achieve your career goals.', 'Bạn có kế hoạch tài chính cá nhân không? Hãy chia sẻ cách bạn tiếp cận việc quản lý tài chính để đạt được mục tiêu nghề nghiệp.'),
  ('Start a business or work for hire', 'Khởi nghiệp hay làm thuê', 'Do you want to start a business in the future?Let''s analyze the pros and cons of starting a business versus working for an organization.', 'Bạn có muốn khởi nghiệp trong tương lai không? Hãy phân tích ưu và nhược điểm của việc khởi nghiệp so với làm việc cho tổ chức.'),
  ('Develop digital skills', 'Phát triển kỹ năng số', 'Digital technology is changing every industry.What digital skills are you developing and why do you think they are important?', 'Công nghệ số đang thay đổi mọi ngành nghề. Bạn đang phát triển những kỹ năng số nào và tại sao bạn cho chúng là quan trọng?'),
  ('Core values ​​at work', 'Giá trị cốt lõi trong công việc', 'What values ​​are most important to you at work?Describe a situation in which you acted on those values ​​despite difficulties.', 'Những giá trị nào quan trọng nhất với bạn trong công việc? Hãy mô tả một tình huống bạn đã hành động theo những giá trị đó dù gặp khó khăn.'),
  ('Professional ethics', 'Đạo đức nghề nghiệp', 'Describe a situation in which you faced an ethical issue at work or study.How did you handle it?', 'Hãy mô tả một tình huống bạn phải đối mặt với vấn đề đạo đức trong công việc hoặc học tập. Bạn đã xử lý nó như thế nào?'),
  ('Social responsibility', 'Trách nhiệm xã hội', 'What responsibility do you think businesses and individuals have to society?Please share your perspective and how you carry out that responsibility.', 'Bạn nghĩ doanh nghiệp và cá nhân có trách nhiệm gì với xã hội? Hãy chia sẻ quan điểm của bạn và cách bạn thực hiện trách nhiệm đó.'),
  ('Fairness and equality', 'Công bằng và bình đẳng', 'Have you ever witnessed or experienced injustice?How did you react and how did it influence your perspective?', 'Bạn đã từng chứng kiến hoặc trải qua sự bất công chưa? Bạn đã phản ứng như thế nào và điều đó ảnh hưởng đến quan điểm của bạn ra sao?'),
  ('Honesty at work', 'Tính trung thực trong công việc', 'Tell me about a time when you had to choose between honesty and personal gain.How did you decide and why?', 'Hãy kể về một lần bạn phải lựa chọn giữa sự trung thực và lợi ích cá nhân. Bạn đã quyết định như thế nào và tại sao?'),
  ('Environmental impact', 'Tác động môi trường', 'What responsibility do you think your generation has towards the environment?What are you doing or want to do to contribute to sustainability?', 'Bạn nghĩ thế hệ của mình có trách nhiệm gì với môi trường? Bạn đang làm gì hoặc muốn làm gì để đóng góp cho sự bền vững?');

-- ── NOTES FOR CODE MIGRATION ────────────────────────────────────────────
-- Old columns removed: title, prompt_text, lang
-- New columns: title_en, title_vi, prompt_text_en, prompt_text_vi
-- Query pattern:
--   SELECT title_vi, prompt_text_vi FROM core.essay_prompts  -- Vietnamese
--   SELECT title_en, prompt_text_en FROM core.essay_prompts  -- English
--   SELECT title_en, title_vi, prompt_text_en, prompt_text_vi FROM core.essay_prompts  -- Both
-- API response should include both languages and let FE pick based on user locale.